"""Compose agent-facing prompt files from reusable fragments.

Design: fragments are the single source of truth. Targets are thin
declarative recipes — which fragments, in what order, under what
header. Adding a new target (e.g. Cursor, Aider) is ≤ 10 lines.

Each rendered output is wrapped with two HTML-comment markers so
`kb-write doctor` can detect drift (user hand-edited the generated
file) and `kb-write init --refresh` can regenerate without clobbering
any user-custom section appended AFTER the end marker.
"""
from __future__ import annotations

from dataclasses import dataclass
from importlib import resources
from typing import Sequence


# Markers wrapping the generated portion of a rendered prompt file.
# Anything BETWEEN these markers is managed by kb-write and will be
# overwritten by `init --refresh`. Anything outside them (e.g. after
# the end marker) is preserved across refreshes, letting users add
# their own custom instructions without losing them.
GEN_BEGIN = "<!-- kb-write generated: DO NOT EDIT inside this block -->"
GEN_END = "<!-- kb-write generated end -->"


@dataclass
class Target:
    """A declarative recipe for rendering one agent-facing prompt file."""
    filename: str                      # relative to kb_root, e.g. "CLAUDE.md"
    header: str                        # markdown heading for the file
    intro: str                         # 1-3 sentence intro above fragments
    fragments: Sequence[str]           # ordered list of fragment filenames (no path)
    target_note: str = ""              # optional footer explaining who reads it


# Declarative registry. Add new entries here when a new agent tool
# enters the picture.
TARGETS: list[Target] = [
    Target(
        filename="CLAUDE.md",
        header="# Claude Code instructions for this KB",
        intro=(
            "This repo is an AI-facing knowledge base (ee-kb). Before doing "
            "anything substantive here, follow the steps below."
        ),
        fragments=[
            "discovery.md",
            "cross_platform.md",
            "installation.md",
            "citation_workflow.md",
            "write_workflow.md",
            "search_hint.md",
            "prefs_handling.md",
        ],
        target_note=(
            "> This file is regenerated by `kb-write init --refresh` from "
            "fragments under `kb_write/prompts/fragments/`. Edit those, not "
            "this file. Content you add AFTER the `kb-write generated end` "
            "marker is preserved across refreshes."
        ),
    ),
    Target(
        filename="AGENTS.md",
        header="# Agent instructions for this KB",
        intro=(
            "This file is read by `opencode` (and any other agentic coding "
            "tool that looks for `AGENTS.md` by convention). The content "
            "mirrors `CLAUDE.md` — both come from the same fragments."
        ),
        fragments=[
            "discovery.md",
            "cross_platform.md",
            "installation.md",
            "citation_workflow.md",
            "write_workflow.md",
            "search_hint.md",
            "prefs_handling.md",
        ],
        target_note=(
            "> Regenerate with `kb-write init --refresh`. To change what "
            "any agent sees, edit the fragments — not this file."
        ),
    ),
    Target(
        filename="README.md",
        header="# ee-kb — Knowledge Base",
        intro=(
            "This directory is an AI-facing Markdown knowledge base, synced "
            "from Zotero via `kb-importer` and queried/written by agents via "
            "`kb-mcp` and `kb-write`. See `AGENT-WRITE-RULES.md` for the "
            "normative rules every agent (human or AI) must follow."
        ),
        fragments=[
            "workspace_layout.md",
            "installation.md",
            "citation_workflow.md",
            "directory_map.md",
            "discovery.md",
            "cross_platform.md",
        ],
        target_note=(
            "## Tools\n\n"
            "- `kb-importer` — syncs papers/notes from Zotero.\n"
            "- `kb-mcp` — search, indexer, MCP server. `kb-mcp index` after "
            "bulk changes.\n"
            "- `kb-write` — unified write CLI + Python API. All writes go "
            "through here for validation + atomic replace + git commit."
        ),
    ),
    # Cursor reads `.cursorrules` at the project root for AI context.
    # Content mirrors CLAUDE.md / AGENTS.md — same fragments.
    Target(
        filename=".cursorrules",
        header="# Cursor instructions for this KB",
        intro=(
            "This repo is an AI-facing knowledge base (ee-kb). Cursor reads "
            "this file at startup; the same content lives at `CLAUDE.md` "
            "(Claude Code) and `AGENTS.md` (opencode) — all derive from the "
            "shared fragments under `kb_write/prompts/fragments/`."
        ),
        fragments=[
            "discovery.md",
            "cross_platform.md",
            "installation.md",
            "citation_workflow.md",
            "write_workflow.md",
            "search_hint.md",
            "prefs_handling.md",
        ],
        target_note=(
            "> Regenerate with `kb-write init --refresh`. To change what "
            "any agent sees, edit a fragment — not this file."
        ),
    ),
    # Aider reads `.aiderrc` (or conventions baked via `read` directives).
    # We generate `.aider.conf.yml` would also work; using a flat
    # Markdown doc named `.aiderrc` and letting the user point Aider
    # at it is the simplest cross-version-safe option.
    Target(
        filename=".aiderrc",
        header="# Aider instructions for this KB",
        intro=(
            "This repo is an AI-facing knowledge base (ee-kb). If you are "
            "running Aider here, load this file as conventions (e.g. `aider "
            "--read .aiderrc`). Same content as `CLAUDE.md` / `AGENTS.md` / "
            "`.cursorrules`; change the fragments, not this file."
        ),
        fragments=[
            "discovery.md",
            "cross_platform.md",
            "installation.md",
            "citation_workflow.md",
            "write_workflow.md",
            "search_hint.md",
            "prefs_handling.md",
        ],
        target_note=(
            "> Regenerate with `kb-write init --refresh`."
        ),
    ),
]


def load_fragment(name: str) -> str:
    """Read one fragment from the package's fragments/ directory."""
    pkg = resources.files("kb_write.prompts.fragments")
    return (pkg / name).read_text(encoding="utf-8")


def render_target(target: Target) -> str:
    """Compose a Target into its final Markdown string."""
    parts: list[str] = []
    parts.append(target.header)
    parts.append("")
    parts.append(GEN_BEGIN)
    parts.append("")
    parts.append(target.intro)
    parts.append("")
    for frag_name in target.fragments:
        frag = load_fragment(frag_name).strip()
        # Strip the "<!-- fragment: name -->" header comment for
        # rendered output cleanliness.
        lines = frag.splitlines()
        if lines and lines[0].startswith("<!-- fragment:"):
            lines = lines[1:]
        parts.append("\n".join(lines).strip())
        parts.append("")
    if target.target_note:
        parts.append("---")
        parts.append("")
        parts.append(target.target_note)
        parts.append("")
    parts.append(GEN_END)
    parts.append("")
    return "\n".join(parts)


def render_all() -> dict[str, str]:
    """Render every target; returns {filename: content}."""
    return {t.filename: render_target(t) for t in TARGETS}


def has_generated_block(content: str) -> bool:
    """Detect whether a file was produced by this renderer."""
    return GEN_BEGIN in content and GEN_END in content


def preserve_user_suffix(existing: str, new_generated: str) -> str:
    """When refreshing an existing file, keep anything the user appended
    AFTER the GEN_END marker.

    If `existing` has a GEN_END, the suffix is the text after it.
    If `existing` was hand-written (no markers), the whole file is
    treated as user content and appended after the new generated
    block — with a separator to make the transition obvious.
    """
    if GEN_END in existing:
        suffix = existing.split(GEN_END, 1)[1]
        # Trim a leading blank line to avoid piling up.
        return new_generated + suffix.lstrip("\n")
    # Legacy / hand-written file: preserve it as user-custom.
    if existing.strip():
        return (
            new_generated
            + "\n<!-- user-custom content below (kept from prior version) -->\n\n"
            + existing
        )
    return new_generated
